services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ${DB_USER:-myuser}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # for development
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  mitmproxy:
    build: server/mitmproxy-container
    ports:
      - "${PROXY_PORT:-8080}:8080"
    environment:
      CLASSROOM_ID: ${CLASSROOM_ID:-1}
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: ${DB_USER:-myuser}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mydatabase
    networks:
      - internal
    volumes:
      - "./.mitmproxy:/root/.mitmproxy:z"

  dns:
    image: coredns/coredns
    command: -conf /etc/coredns/Corefile
    volumes:
      - "./server/dns/Corefile:/etc/coredns/Corefile"
    ports:
      - "5223:53/udp"

  backend:
    build: server/server-backend
    ports:
      - "8000:8000"
    networks:
      - internal
      - frontback
    environment:
      CLASSROOM_ID: ${CLASSROOM_ID:-1}
      DB_HOST: mysql_db
      DB_USER: ${DB_USER:-myuser}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: mydatabase
      NOCORS: true

  frontend:
    build: frontend
    networks:
      - frontback
    ports:
      - "3000:3000"

networks:
  internal:
  frontback:

volumes:
  mysql_data: