services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: IeP8aiji
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: IeP8aiji
    ports:
      - "3306:3306" # for development
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  mitmproxy:
    build: mitmproxy-container
    #command: ["sleep", "1000"]
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:

volumes:
  mysql_data: